services:
  - type: web
    name: nursery-scheduler-api
    env: node
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: nursery-scheduler-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

  - type: web
    name: nursery-scheduler-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: nursery-scheduler-db
    databaseName: nursery_scheduler
    user: nursery_user
    plan: free
