services:
  - type: web
    name: nursery-scheduler-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: nursery-scheduler-api
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: nursery-scheduler-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: nursery-scheduler-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

  - type: redis
    name: nursery-scheduler-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  - name: nursery-scheduler-db
    databaseName: nursery_scheduler
    user: nursery_user